# NumPy HandOut

### Question 1: Make an array of 100 element and increase individual item with 1

In [1]:
import numpy as np

In [2]:
a=np.random.randint(1,1000,100)
a

array([232, 232, 453, 134, 594, 629, 816, 660, 386, 576, 196, 905,  62,
       568, 275, 609, 165, 100, 932, 705, 453, 980, 105, 384, 505, 533,
       496, 667, 631, 280, 902, 842, 378, 242, 463, 248, 590, 445, 148,
       768, 149, 693, 905, 279, 711, 440, 643, 820,  46, 825, 147, 965,
       182, 657, 361, 535, 762, 661, 434, 173, 361, 656, 927, 636, 384,
       946, 368, 424, 180, 468, 524, 457, 493, 303, 795, 780, 516, 593,
       798, 132, 800, 478, 611, 932, 167, 905, 563, 113, 108, 758, 288,
        90, 266,  14, 135, 332, 178, 181, 529, 593])

In [3]:
a=a+1
a

array([233, 233, 454, 135, 595, 630, 817, 661, 387, 577, 197, 906,  63,
       569, 276, 610, 166, 101, 933, 706, 454, 981, 106, 385, 506, 534,
       497, 668, 632, 281, 903, 843, 379, 243, 464, 249, 591, 446, 149,
       769, 150, 694, 906, 280, 712, 441, 644, 821,  47, 826, 148, 966,
       183, 658, 362, 536, 763, 662, 435, 174, 362, 657, 928, 637, 385,
       947, 369, 425, 181, 469, 525, 458, 494, 304, 796, 781, 517, 594,
       799, 133, 801, 479, 612, 933, 168, 906, 564, 114, 109, 759, 289,
        91, 267,  15, 136, 333, 179, 182, 530, 594])

### Question 2:Define a array of 10 continous elements and then Square every elemnts present in that 

In [4]:
b=np.arange(1,10)
b

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [5]:
b=b**2
b

array([ 1,  4,  9, 16, 25, 36, 49, 64, 81], dtype=int32)

### Question 3:Make an 2D-array having size 3X3 with diagonal elemnts as 1,2,3 and then subtract 1 from every element ?

In [13]:
c=np.diag([1,2,3])
d=np.ones((3,3))
print(c)
print(d)
c=c-d
print(c)

[[1 0 0]
 [0 2 0]
 [0 0 3]]
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
[[ 0. -1. -1.]
 [-1.  1. -1.]
 [-1. -1.  2.]]


### Question 4: Make 2 matrix and multiply both matrix and then calculate dot product values?

In [17]:
e=np.array([1,2,3,4])
f=np.array([1,2,3,4])
print(e*f)
print("*******")
print(e.dot(f))


[ 1  4  9 16]
*******
30


### Question 5: Compare two array elements? (A) Equal(Every element (B) > (C) Exactly equal

In [18]:
g=np.random.randint(1,100,4)
h=np.random.randint(1,100,4)
print(g)
print(h)

[57 91 98 62]
[24  4  8 92]


In [19]:
g==h #Compare each element is satisfying every element

array([False, False, False, False])

In [20]:
g>h #Compare each element is satisfying every element

array([ True,  True,  True, False])

In [22]:
np.array_equal(g,h) # Best way to compare two array's element

False

### Question 6: Make 2 array of bollen type and do following operations: (A) OR  (B)  AND

In [2]:
a=np.array([1,0,1,1], dtype=bool)
b=np.array([0,0,1,0], dtype=bool)

In [3]:
np.logical_or(a,b)

array([ True, False,  True,  True])

In [4]:
np.logical_and(a,b)

array([False, False,  True, False])

### Question 7: Make an array and do following operations: (A) summation (B) summation Row wise (C) summation Column wise 

In [5]:
a=np.array([1,2,3,4])
np.sum(a)

10

In [12]:
a=np.array([[1,2,3,4],[5,6,7,8]])
print(a.sum(axis=0))
print(a.sum(axis=1))
print(a.sum())

[ 6  8 10 12]
[10 26]
36


### Question 8: Make an array and do find: (A) Minimum Element (B) Maximum element (C) Index of minimum element (D) Index of maximum element 

In [14]:
a=np.random.randint(1,10000,100)
a

array([4928,  386, 2206, 3353, 7349, 8131, 7468, 1800, 1218, 7446, 4264,
       5904, 7897, 7818, 9987, 2111, 2155, 8488, 7848, 5738, 1364, 1707,
       6601,  418, 4454, 5768, 9359, 2590, 4755, 8587, 9282, 7203, 7393,
       1084, 4059, 7845, 1551, 1688, 8190, 5506,  516, 8213, 7141,  849,
       2416, 4822, 9010,  257, 9682, 2333,  287, 5517, 1690, 7655, 7584,
       1425,  943, 4449, 6034,  401, 8442, 9109, 3015, 6924, 4870, 7125,
       2083, 1145, 9038, 8099, 4146, 2003, 3191, 1840,  522, 8589, 8454,
       4944, 7405, 4701, 5139,  299, 1034,  787, 4573,  872, 2439, 4152,
       2242,   23, 2716, 7633, 8514, 7919, 9719, 6937, 9739, 5585,  585,
       7127])

In [15]:
print(a.max())
print(a.min())
print(a.argmax())
print(a.argmin())

9987
23
14
89


### Question 9: Make 2D array and check wether it is a zero matrix or not?

In [18]:
a=np.zeros((5,5))
a

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [19]:
print(np.any(a!=0))
#or
print(np.all(a==0))

False
True


### Thanks, 

### Shubham Sagar

### DM for any assist: www.instagaram.com/shubhamthrills